# Generated by Django 6.0.2 on 2026-03-10 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='The name of the sport')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Sport',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sportsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Article title')),
                ('content', models.TextField(blank=True, verbose_name='Article content')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Photo')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Time of last modification')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publication')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sportsmen.sports', verbose_name='Sports')),
            ],
            options={
                'verbose_name': 'Sports news',
                'verbose_name_plural': 'Sports news',
                'ordering': ['time_create', 'title'],
            },
        ),
    ]
