# Generated by Django 6.0.2 on 2026-02-27 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sportsmen.sports')),
            ],
        ),
    ]
