# Generated by Django 6.0.2 on 2026-02-27 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmen', '0002_sports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sports',
            name='sport',
        ),
        migrations.AddField(
            model_name='sportsman',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sportsmen.sports'),
        ),
    ]
