# Generated by Django 6.0.2 on 2026-03-05 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmen', '0003_remove_sports_sport_sportsman_sport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sports',
            options={'ordering': ['name'], 'verbose_name': 'Sport'},
        ),
        migrations.AlterModelOptions(
            name='sportsman',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Sports news', 'verbose_name_plural': 'Sports news'},
        ),
        migrations.AlterField(
            model_name='sports',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='The name of the sport'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='content',
            field=models.TextField(blank=True, verbose_name='Article content'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publication'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sportsmen.sports', verbose_name='Sports'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Time of last modification'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Article title'),
        ),
    ]
